@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyBagel <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Bagel
Class ReadOnlyBagel
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Flashcard {
Class Flashcard
Class Title
Class Description
Class Tag
Class FlashcardSet
Class Link
Class UniqueFlashcardList
class SetOfFlashcardSets
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Bagel .up.|> ReadOnlyBagel

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Bagel
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Bagel *--> "1" UniqueFlashcardList
Bagel *--> "1" SetOfFlashcardSets
UniqueFlashcardList o--> "*" Flashcard
SetOfFlashcardSets o--> "*" FlashcardSet
Flashcard *--> Title
Flashcard *--> Description
Flashcard *--> FlashcardSet
Flashcard *--> Link
Flashcard *--> "*" Tag

Title -[hidden]right-> Description
Description -[hidden]right-> FlashcardSet
FlashcardSet -[hidden]right-> Link
SetOfFlashcardSets -[hidden]right-> UniqueFlashcardList

ModelManager -->"1" Flashcard : filtered list
@enduml
