@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":BagelParser" as BagelParser LOGIC_COLOR
participant ":ViewCommandParser" as ViewCommandParser LOGIC_COLOR
participant "vc:ViewCommand" as ViewCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("view 1")
activate LogicManager

LogicManager -> BagelParser : parseCommand("view 1")
activate BagelParser

create ViewCommandParser
BagelParser -> ViewCommandParser
activate ViewCommandParser

ViewCommandParser --> BagelParser
deactivate ViewCommandParser

BagelParser -> ViewCommandParser : parse("1")
activate ViewCommandParser

create ViewCommand
ViewCommandParser -> ViewCommand
activate ViewCommand

ViewCommand --> ViewCommandParser : vc
deactivate ViewCommand

ViewCommandParser --> BagelParser : vc
deactivate ViewCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCommandParser -[hidden]-> BagelParser
destroy ViewCommandParser

BagelParser --> LogicManager : vc
deactivate BagelParser

LogicManager -> ViewCommand : execute()
activate ViewCommand

ViewCommand -> Model : updateFilteredFlashcardList(predicateViewFlashcard);
activate Model

Model --> ViewCommand
deactivate Model

create CommandResult
ViewCommand -> CommandResult
activate CommandResult

CommandResult --> ViewCommand
deactivate CommandResult

ViewCommand --> LogicManager : result
deactivate ViewCommand

[<--LogicManager
deactivate LogicManager
@enduml
